const LEVELS = [
  [
    "                                                                                                                                        ",
    "                                                                                                                                        ",
    "                                                                    p       p                                                           ",
    "                                                                    r       r                ppp          c                             ",
    "                                                                s       s       s                                                       ",
    "                                                                p       p       p       ppp  sss          s           ss                @",
    "                                                        pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp",
    "                                                                                                                                        ",
    "                                                   ppp                                                                                  ",
    "                                                c                                                                                       ",
    "                                               ppp                                                                                      ",
    "                                                                                                                                        ",
    "         s              s      ss          pppssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  ],
  [
    "                                                                                                                                        ",
    "                                                                                                                                        ",
    "                                                                                                                                        ",
    "                                                                pp            pppp                                                              ",
    "                                                                rr pp         rrrr                                                              ",
    "                                               ss   ss     s       rr                                                                                                ",
    "                                           pppppppppppppppppppp                                                                                                                ",
    "                                     pp                        ppp          ppppppppp                                                                              ",
    "                                pp                                ppppppppppppppppppp     pp     ppp           c                                                                        ",
    "                           pp                                                                                 ppp                        ",
    "                      pp                    ss     s    s      c                                        ppp                                            ",
    "                 pp          pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp             ",
    "       pppppppssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss                                @",
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  ],
  [
    "                                                                                                                                        ",
    "                                                                                                                                        ",
    "                                                                                                                                        ",
    "                                                                                  c                                                      ",
    "                                                                                 pp                                                        ",
    "                                                                                                                                        ",
    "                                                        c                    ppp                                           ss               ",
    "                                       ppppppppppppppppppppppppppppp   ppp            ppp    pp    pp    pp    pp    pp    pp            ",
    "                                  pp                                                                                                        ",
    "                                                                                 ppp                                                   ",
    "                              pp                                                                                                          ",
    "           s       s                          s            ss      sss     ppp                                                     @",
    "           p       pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppssssssssssssssssssssssssssssssspppppppppppppppppp ",
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbsssssssssssssssssssssssssssssssssssssssssss                                                   ",
  ]
];

const levelConf = {
  width: 64,
  height: 64,
  b: () => [sprite("lvl1_platform"), solid(), area(), "block"],
  p: () => [sprite("lvl1_platform"), solid(), area(), "platform"],
  s: () => [sprite("lvl1_spike"), area(), "spike"],
  r: () => [sprite("lvl1_spike", { flipY: true }), area(), "spike"],
  c: () => [sprite("coin", { width: 64, height: 64 }), area(), "coin"],
  "@": () => [
    sprite("portal", {
      height: height(),
      width: 50,
    }),
    solid(),
    area({ scale: 0.5 }),
    origin("center"),
    "portal",
  ],
  "t": () => [
    sprite("portal", {
      height: height(),
      width: 50,
    }),
    solid(),
    area({ scale: 0.5 }),
    origin("center"),
    "reversePortal",
  ]};
